export const REQUEST_EMOTIONS = 'request-emotions'
export const RECEIVE_EMOTIONS = 'receive-emotions'
export const MOUNT_WEBCAM = 'mount-webcam'
export const PROPAGATE_TIME = 'propagate-time'
export const RECEIVE_SPEECH = 'receive-speech'
